dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  # to install deb file of stable chrome https://stackoverflow.com/a/62432435
  apt:
    packages:
      - dpkg
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm ci --no-optional

script:
  - npm run testCI
  - npm run e2eCI
